{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparkset.fullname" . }}-mysql-secret
  labels:
    {{- include "sparkset.mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  password: {{ .Values.mysql.auth.password | quote }}
{{- end }}



