{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparkset.fullname" . }}-mysql
  labels:
    {{- include "sparkset.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "sparkset.mysql.selectorLabels" . | nindent 4 }}
{{- end }}



